### ISSUE TITLE
There should be a better way of doing jobs and progressing that isn't just hoping you get reached out to on Twitter

### ISSUE THREAD

**Issue by ghost** [echoroleplay/feedback#194]
I think that crime is in a bad spot right now, this is because sitting on Twitter and praying that you get reached out to by Dr.Lamb isn't a fun system.

A couple recommendations would be bringing back a thermite table, so at least one job is able to be done without being called and given stuff. I think this is needed  because newer gangs who lamb doesn't know about are never reached out to. One possible fix to this is that lamb should be in the echo gangs discord so he can see all of the whitelisted gangs and see the turf map. Or if Lamb is able to give certain respected gangs job items (not just remote cards, nobody wanted to pay 2k for 8 loose notes respectfully) so that they can actually have positive rp with smaller groups through reaching out and doing deals with people.

Crime is just really unfulfilling at the moment for criminal groups who don't want to just be primarily shooting gangs, without the weekend thermite events, it would have been three weeks of no jobs, it's hard to keep people motivated when the best way to make money is scrapping cars. I get that we could hit houses or whatever too,  but neither are nearly as fun or satisfying as doing a store the old way, or a jewelry store.

The other job that was available was drug runs, which I think was in a good spot, but is definitely one of the "hardcore" jobs and it's hard to invite the newer or non-shooter members because nobody wants to lose 50-80k depending on loadout, compared to the 8k for a vangies, but for some reason the job was changed to not allow people with no "rep" which has no definable variable that is clear for people to work towards, and drug runs not being available is tough because it was a good way to get guns for groups who are not reached out to by gun plugs, or have no interest in getting whitelisted. I think that maybe with drug runs instead of a rep system maybe have the needed drugs returned or something that is clear and makes it harder to hit. If there are any questions for me I will be happy to answer

**Comment by Lane2G** [comment]
+100 However crafting will never come back 
I feel like I can’t do crime unless One group permits it and good luck getting anything else from other gangs they have to feed they’re own first. Whole system is super bottle necked and honestly a huge let down

**Comment by TwoTaDile** [comment]
I think there is a lot of growing pains and even though I've seen crafting be brought up and shot down multiple times there has to be a solution that can make everything more equal. I think that materials had a lot of RP value when it came to a suspended secondary market which allowed people from all walks of life to make meaningful connections with gangs to eventually elevate into more RP.  Overall I don't like that the heavy reliance on established groups for jobs is recurring making it even harder for people to do low and even high end crime that has value.

**Comment by FlawwsX** [comment]
We are working to improve this, thank you for your suggestion.

**Comment by BigDev1122** [comment]
Lots of growing pain, but thats not to say we dont enjoy the updated things brought out. Houses was a huge game changer (once alarms are fixed) Gives plenty of crims a way into the crim world. But then after that, the only thing not gate kept is drugs.                          I can see why they want it gate kept in some way, as before so much was going on for cops. We would do banks and most of the time not even one cop would show up. Keeping it locked behind one person was just not a good ideal. lamb we love and fuck with you. but you cant be here 24/7 with everything you do. And because of that now its certain gangs who only get the stuff. How was this not a thought it would go south very fast. Lamb has his list of people who will get it. That cant be fair when the human aspect of this comes into play. As he would obviously choose the people he has good relationships with. The rp with lamb sometimes isn't the best with rp, as for example a few days ago lamb was playing his cop, switched to someone else, loaded a van up with stuff, parked somewhere, screenshotted his screen., sent it to whoever, homie pulled up. said some stuff to lamb, lamb didn't respond and he went about his day. And dont take this as it strictly hate to lamb. Its an example of why this system is flawed to have things gate kept by people. It doesn't work.
