### ISSUE TITLE
pause menu map being buggy

### ISSUE THREAD

**Issue by RADSTAR55** [echoroleplay/feedback#268]
pause menu Map being buggy

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. try and click a blip

**Expected Behaviour:** the cross hair highlights the blip 

**Actual Behaviour:** doesn't work (honestly watch the vid)

**Screenshot(s)/Video(s):** https://medal.tv/games/gta-v/clips/1hI74pE_YlbBQQ/d133738nKr6c?invite=cr-MSxxTEUsMTc5NzI4NDkzLA

**Comment by oRexr1337** [comment]
might just be you, i tried clicking on some of the blips you showed as examples in the video and they worked as normal.

**Comment by RADSTAR55** [comment]
Interesting, I know that a few others on duty where having issues

**Comment by TomatenCas** [comment]
Having the same issue, might be a cop thing then

**Comment by JustJangar** [comment]
yep, every cop I asked has the same issue:
https://medal.tv/games/gta-v/clips/1hFTSGk3yE5R1h/d13373xLRAa4?invite=cr-MSxQdE8sNDk3MzY4MDMs

**Comment by JustJangar** [comment]
Seems to only happen when transponder is on and on duty I think.
Off duty without transponder seems to work fine.

**Comment by MamaPrince** [comment]
I was having this issue as well.

**Comment by MamaPrince** [comment]
Actually might have just been a restart thing. Issue no longer persists

**Comment by MrJayGamerTTV** [comment]
I've had this issue on and off for the past month at least. It's not everyday, but still occasionally, usually fixes upon server restart. I believe it is also linked with an issue, where if you try to move down (south) in the map, it will eventually stop to a specific point, and not let you move the map all the way down. Usually this southmost point will be the southernmost officer transponder.

Say, I was doing some messing around on my localhost server testing things, and I encountered the same issue there. And this issue I fixed, by making sure that all the map blip coordinates had at least one decimal in them, even if said decimal would be 0. So meaning (on the examples, note the y-coordinate):

vector3(-1602.6, -1046, 12.3) - This will not work, whereas:
vector3(-1602.6, -1046.0, 12.3) - This will work just fine, with no issues whatsoever.

So I might recommend having a look into that, seeing to make sure that the transponders will give the officer's location with decimal points, always, instead of without, and that should eliminate the issue fully.
