### ISSUE TITLE
GoPostal Not Paying Out Every Other Delivery

### ISSUE THREAD

**Issue by Bountyrogger** [echoroleplay/feedback#366]
While doing GoPostal every other stop is not paying out like it did prior to the economy wipe. Doesn't matter the distance either

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Go get a PoPostal Van and Start your route
2. Go to the first stop and deliver the package, money deposited into your account
3. Go to the second stop and deliver the package. Get no message about money earned and no new history in the bank app

**Expected Behavior:** Get paid for every stop on the run

**Actual Behavior:** Wasting time every other stop sometimes up to being 4 miles...

**Screenshot(s)/Video(s):** My Medal is acting up so unable to get a clip of it

**Comment by karichandesu** [comment]
You are technically picking up a package on the first stop, dropping off at the second, that's why the payout is the way that it is. I did submit a change for it so when you receive the truck at GoPostal, you get a set amount of packages to deliver so it pays out at every delivery and you can complete a whole run, a bit more realistically, here: https://github.com/echoroleplay/feedback/issues/305
